/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Jul 29 01:52:35 2019. */

#include "notify.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TestMessage_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, TestMessage, currtime, currtime, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
