// Code generated by protoc-gen-go. DO NOT EDIT.
// source: btnMsg.proto

package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ButtonMessage struct {
	Building             *int32   `protobuf:"varint,1,req,name=building" json:"building,omitempty"`
	Room                 *int32   `protobuf:"varint,2,req,name=room" json:"room,omitempty"`
	LedOn                *bool    `protobuf:"varint,3,req,name=ledOn" json:"ledOn,omitempty"`
	Label                *string  `protobuf:"bytes,4,req,name=label" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ButtonMessage) Reset()         { *m = ButtonMessage{} }
func (m *ButtonMessage) String() string { return proto.CompactTextString(m) }
func (*ButtonMessage) ProtoMessage()    {}
func (*ButtonMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_btnMsg_c2ed35b749ec82d5, []int{0}
}
func (m *ButtonMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ButtonMessage.Unmarshal(m, b)
}
func (m *ButtonMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ButtonMessage.Marshal(b, m, deterministic)
}
func (dst *ButtonMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ButtonMessage.Merge(dst, src)
}
func (m *ButtonMessage) XXX_Size() int {
	return xxx_messageInfo_ButtonMessage.Size(m)
}
func (m *ButtonMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ButtonMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ButtonMessage proto.InternalMessageInfo

func (m *ButtonMessage) GetBuilding() int32 {
	if m != nil && m.Building != nil {
		return *m.Building
	}
	return 0
}

func (m *ButtonMessage) GetRoom() int32 {
	if m != nil && m.Room != nil {
		return *m.Room
	}
	return 0
}

func (m *ButtonMessage) GetLedOn() bool {
	if m != nil && m.LedOn != nil {
		return *m.LedOn
	}
	return false
}

func (m *ButtonMessage) GetLabel() string {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return ""
}

func init() {
	proto.RegisterType((*ButtonMessage)(nil), "main.ButtonMessage")
}

func init() { proto.RegisterFile("btnMsg.proto", fileDescriptor_btnMsg_c2ed35b749ec82d5) }

var fileDescriptor_btnMsg_c2ed35b749ec82d5 = []byte{
	// 126 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2a, 0xc9, 0xf3,
	0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xca,
	0xe6, 0xe2, 0x75, 0x2a, 0x2d, 0x29, 0xc9, 0xcf, 0xf3, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15,
	0x92, 0xe2, 0xe2, 0x48, 0x2a, 0xcd, 0xcc, 0x49, 0xc9, 0xcc, 0x4b, 0x97, 0x60, 0x54, 0x60, 0xd2,
	0x60, 0x0d, 0x82, 0xf3, 0x85, 0x84, 0xb8, 0x58, 0x8a, 0xf2, 0xf3, 0x73, 0x25, 0x98, 0xc0, 0xe2,
	0x60, 0xb6, 0x90, 0x08, 0x17, 0x6b, 0x4e, 0x6a, 0x8a, 0x7f, 0x9e, 0x04, 0x33, 0x50, 0x90, 0x23,
	0x08, 0xc2, 0x01, 0x8b, 0x26, 0x26, 0xa5, 0xe6, 0x48, 0xb0, 0x00, 0x45, 0x39, 0x83, 0x20, 0x1c,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1c, 0x21, 0x68, 0xeb, 0x81, 0x00, 0x00, 0x00,
}
