apiVersion: v1
kind: Pod
metadata:
  name: pi-hello
  namespace: hello-namespace
  labels:
    env: test
spec:
  nodeName: pihome
  containers:
    - name: hello
      image: jonas27/hello:v5arm
      imagePullPolicy: Always
      ports:
        - containerPort: 3000
