/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Mon Jul 29 09:27:20 2019. */

#ifndef PB_NOTIFY_PB_H_INCLUDED
#define PB_NOTIFY_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ButtonMessage {
    int32_t milli;
    int32_t sec;
    char label[40];
/* @@protoc_insertion_point(struct:ButtonMessage) */
} ButtonMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ButtonMessage_init_default               {0, 0, ""}
#define ButtonMessage_init_zero                  {0, 0, ""}

/* Field tags (for use in manual encoding/decoding) */
#define ButtonMessage_milli_tag                  1
#define ButtonMessage_sec_tag                    2
#define ButtonMessage_label_tag                  3

/* Struct field encoding specification for nanopb */
extern const pb_field_t ButtonMessage_fields[4];

/* Maximum encoded size of messages (where known) */
#define ButtonMessage_size                       64

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define NOTIFY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
