apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello-namespace
spec:
  type: NodePort
  selector:
    app: hello
  ports:
    - name: http
      nodePort: 30001
      port: 3000
      targetPort: 3000
