/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed Jul 31 23:12:21 2019. */

#include "notify.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ButtonMessage_fields[5] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ButtonMessage, building, building, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ButtonMessage, room, building, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, ButtonMessage, ledOn, room, 0),
    PB_FIELD(  4, STRING  , REQUIRED, STATIC  , OTHER, ButtonMessage, label, ledOn, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
