apiVersion: v1
kind: Service
metadata:
  name: {{ include "dockerMirror.fullname" . }}
  labels:
{{ include "dockerMirror.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      port: 5001
      targetPort: 5000
  selector:
    app.kubernetes.io/name: {{ include "dockerMirror.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
