apiVersion: v1
kind: Service
metadata:
  name: {{ include "syncserver.fullname" . }}
  labels:
{{ include "syncserver.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: 30003
      targetPort: 3000
      port: 3000
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.port }}
      nodePort: 30004
      targetPort: 3001
      port: 3001
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "syncserver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
