/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Jul 29 09:27:20 2019. */

#include "notify.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ButtonMessage_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, ButtonMessage, milli, milli, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, ButtonMessage, sec, milli, 0),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, ButtonMessage, label, sec, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
